version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
    # Set version update strategy
    versioning-strategy: increase
    # Add reviewers
    reviewers:
      - 'nickhart'
    # Add assignees
    assignees:
      - 'nickhart'
    # Add commit message
    commit-message:
      prefix: 'chore'
      include: 'scope'
